### ISSUE TITLE
Barrel Connector crashes server occasionally when inserting into Infinite Barrels.

### ISSUE THREAD

**Issue by Routhinator** [LatvianModder/YABBA#140]
I have been running a set of barrels with Integrated Dynamics inserting into them from Roost chickens.. It was running fine until I upgraded them to infinite capacity last night, since then we've had two crashes with the same stack trace.

```
2019-12-16 19:14:57,218 : INFO : java.util.ConcurrentModificationException: null
2019-12-16 19:14:57,218 : INFO : 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_222]
2019-12-16 19:14:57,218 : INFO : 	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_222]
2019-12-16 19:14:57,218 : INFO : 	at com.latmod.yabba.tile.TileItemBarrelConnector.insertItem(TileItemBarrelConnector.java:202) ~[TileItemBarrelConnector.class:?]
2019-12-16 19:14:57,218 : INFO : 	at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:45) ~[ItemHandlerHelper.class:?]
2019-12-16 19:14:57,218 : INFO : 	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:135) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
2019-12-16 19:14:57,218 : INFO : 	at org.cyclops.commoncapabilities.ingredient.storage.IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.insert(IngredientComponentStorageWrapperHandlerItemStack.java:93) ~[IngredientComponentStorageWrapperHandlerItemStack$ComponentStorageWrapper.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.integrateddynamics.core.network.IngredientChannelAdapter.insert(IngredientChannelAdapter.java:133) ~[IngredientChannelAdapter.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.cyclopscore.ingredient.storage.IngredientStorageHelpers.insertIngredientQuantity(IngredientStorageHelpers.java:763) ~[IngredientStorageHelpers.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.cyclopscore.ingredient.storage.IngredientStorageHelpers.insertIngredient(IngredientStorageHelpers.java:787) ~[IngredientStorageHelpers.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.cyclopscore.ingredient.storage.IngredientStorageHelpers.moveIngredientsSlotted(IngredientStorageHelpers.java:401) ~[IngredientStorageHelpers.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.cyclopscore.ingredient.storage.IngredientStorageHelpers.moveIngredientsSlotted(IngredientStorageHelpers.java:314) ~[IngredientStorageHelpers.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.integratedtunnels.core.TunnelHelpers.moveSingle(TunnelHelpers.java:61) ~[TunnelHelpers.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.integratedtunnels.core.TunnelHelpers.moveSingleStateOptimized(TunnelHelpers.java:133) ~[TunnelHelpers.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.integratedtunnels.part.aspect.TunnelAspectWriteBuilders$Item.lambda$static$14(TunnelAspectWriteBuilders.java:584) ~[TunnelAspectWriteBuilders$Item.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.write(AspectBuilder.java:429) ~[AspectBuilder$BuiltWriter.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.integrateddynamics.part.aspect.write.AspectWriteBase.update(AspectWriteBase.java:58) ~[AspectWriteBase.class:?]
2019-12-16 19:14:57,219 : INFO : 	at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.update(AspectBuilder.java:452) ~[AspectBuilder$BuiltWriter.class:?]
2019-12-16 19:14:57,220 : INFO : 	at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:96) ~[PartTypeWriteBase.class:?]
2019-12-16 19:14:57,220 : INFO : 	at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:48) ~[PartTypeWriteBase.class:?]
2019-12-16 19:14:57,220 : INFO : 	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:135) ~[PartNetworkElement.class:?]
2019-12-16 19:14:57,220 : INFO : 	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:410) ~[Network.class:?]
2019-12-16 19:14:57,220 : INFO : 	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:65) ~[TickHandler.class:?]
2019-12-16 19:14:57,220 : INFO : 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1816_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
2019-12-16 19:14:57,220 : INFO : 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
2019-12-16 19:14:57,220 : INFO : 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
2019-12-16 19:14:57,220 : INFO : 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
2019-12-16 19:14:57,220 : INFO : 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
2019-12-16 19:14:57,221 : INFO : 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
2019-12-16 19:14:57,221 : INFO : 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

```

Full crash:

https://pastebin.com/t4vvN0rc

**Comment by Routhinator** [comment]
Minecraft 1.12.2
Yabba Verson: 1.1.2.54
Integrated Dynamics: 1.1.1
Forge: 14.23.5.2847

**Comment by Routhinator** [comment]
Hmmm, I just realized I connected a second barrel connector last night with no barrels on it. Could inserting into a connector with no barrels explain the null value?

**Comment by Routhinator** [comment]
Removed the second barrel connector without barrels and retested, same crash happened again 12 hours later.
