### ISSUE TITLE
Game Crash:  java.lang.NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by Protheus** [LatvianModder/YABBA#17]
Below issue only happens when I have Yabba 0.5.0 installed.

Game crash with following error: https://pastebin.com/Qd3pJsCE

java.lang.NullPointerException: Rendering Block Entity
	at mcjty.lib.tools.ItemStackTools.setStackSize(ItemStackTools.java:71)
	at com.latmod.yabba.tile.BarrelTileContainer.getStackInSlot(BarrelTileContainer.java:94)
	at com.latmod.yabba.client.RenderBarrel.renderTileEntityAt(RenderBarrel.java:50)
	at com.latmod.yabba.client.RenderBarrel.func_180535_a(RenderBarrel.java:31)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

- Minecraft 1.10.2
- YABBA-1.10.2-0.5.0
- mcjtylib-1.1x-2.3.11
- FTBLib-1.1x-3.6.1
- Forge"2281

**Issue:**
- I have several Yabba barrels. They are all connected with AE2.
- Go to the end or nether
- Come back to the overworld
- Go to my storage area where the barrels are located and the game will crash.

When using previous version of Yabba (0.4.3), the game crash doesn't happen but all recipes are not active, I think due to using 0.5.0 and then back to 0.4.3 the recipes do not show up in JEI anymore and are not working.

GOing back to 0.5.0 game crash but the recipes are working fine

![capture1](https://cloud.githubusercontent.com/assets/1455178/25586029/b8296cde-2e9d-11e7-843d-c4de369981da.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1455178/25586030/b843fa5e-2e9d-11e7-9578-b14771264544.PNG)

**Comment by Hodel1** [comment]
Ouuu, FTB Beyond 1.6.0 (<24h released before) includes now Yabba 0.5.0
Crashlog: https://pastebin.com/SsfRZndb

@LatvianModder have you contact to the FTB Team? They must downgrade the Yabba Version, if you can't fix it fast, soon as possible, in 1.6.1 :(

we're running further FTB Beyond 1.5.3.

**Comment by Protheus** [comment]
If one downgrades to 0.4.3... the recipes may not work...

**Comment by Hodel1** [comment]
I don't want to spam your tickets, but i would like to report, that i reported this bug by FTB Support

https://support.feed-the-beast.com/t/1-10-2-ftb-beyond-1-6-0-yabba-0-5-0-crash-during-rendering/31944/3

And i recorded a "Howto crash the Server" Video.
To see here: https://youtu.be/C7iV0OH717g

**Comment by LatvianModder** [comment]
Fixed in 0.5.1
