### ISSUE TITLE
java.lang.IllegalStateException: No block found for eucalyptus2 PLANKS non-fireproof

### ISSUE THREAD

**Issue by xKnightGamingx** [LatvianModder/YABBA#41]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  HammerCoreCore (HammerCore-1.12.1-1.9.4.4.jar)
  LoadingPlugin (Quark-r1.3-109.jar)
  SFRCore (SolarFluxReborn_1.12.1-3.40r.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-71.jar)
  AppleCore (AppleCore-mc1.12.1-2.2.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.2.jar)
  CoreModLoader (applied-llamagistics-1.12-rv5-beta-7.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.2.7.jar)
  Plugin (NotEnoughIDs-1.5.4.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 9/10/17 6:41 PM
Description: Initializing game

java.lang.IllegalStateException: No block found for eucalyptus2 PLANKS non-fireproof
	at forestry.arboriculture.WoodAccess.getBlock(WoodAccess.java:239)
	at com.latmod.yabba.integration.ForestryIntegration.registerSkins(ForestryIntegration.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1111_ForestryIntegration_registerSkins_YabbaSkinsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at com.feed_the_beast.ftbl.lib.EventBase.post(EventBase.java:18)
	at com.latmod.yabba.client.YabbaClient.loadModelsAndSkins(YabbaClient.java:169)
	at com.latmod.yabba.client.BarrelModelLoader.func_110549_a(BarrelModelLoader.java:60)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraftforge.client.model.ModelLoaderRegistry.registerLoader(ModelLoaderRegistry.java:74)
	at com.latmod.yabba.YabbaItems.registerModels(YabbaItems.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_374_YabbaItems_registerModels_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1091)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:757)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:606)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at forestry.arboriculture.WoodAccess.getBlock(WoodAccess.java:239)
	at com.latmod.yabba.integration.ForestryIntegration.registerSkins(ForestryIntegration.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1111_ForestryIntegration_registerSkins_YabbaSkinsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at com.feed_the_beast.ftbl.lib.EventBase.post(EventBase.java:18)
	at com.latmod.yabba.client.YabbaClient.loadModelsAndSkins(YabbaClient.java:169)
	at com.latmod.yabba.client.BarrelModelLoader.func_110549_a(BarrelModelLoader.java:60)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraftforge.client.model.ModelLoaderRegistry.registerLoader(ModelLoaderRegistry.java:74)
	at com.latmod.yabba.YabbaItems.registerModels(YabbaItems.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_374_YabbaItems_registerModels_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1091)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:757)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:606)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/YABBA/issues/40
